### **Рабочая тетрадь №2**

1.2.1 Пример
Задача:
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2 Пример
Задача:
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [ ]:
import numpy as np
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10,20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.2.3 Пример
Задача:
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [ ]:
import numpy as np

z = np.random.random((10,10))
zmin, zmax, zmean = z.min(), z.max(), z.mean()
print(zmin, zmax, zmean)

0.010998254029144783 0.9926393968596124 0.4981950960320477


1.2.4 Пример
Задача:
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [ ]:
import numpy as np

a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5 Пример
Задача:
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [ ]:
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


1.2.6 Пример
Задача:
Отсортировать массив.

In [ ]:
import numpy as np

array = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(array))

[1 2 3 4 5 6 7 8]


1.3.1 Задание
Задача:
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy as np

matrix = np.zeros((8, 8))

matrix[::2, ::2] = 1  # Заполняем четные строки и столбцы единицами
matrix[1::2, 1::2] = 1  # Заполняем нечетные строки и столбцы единицами

print(matrix)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


1.3.2 Задание
Задача:
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [ ]:
import numpy as np

z = np.zeros((5,5))
z += np.arange(5)
print(z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


1.3.3 Задание
Задача:
Создать массив 3x3x3 со случайными значениями.

In [ ]:
import numpy as np

# Создаем массив 3x3x3 со случайными значениями
array = np.random.rand(3, 3, 3)

print(array)

[[[0.93399603 0.55582143 0.44344194]
  [0.55851568 0.95403447 0.94362941]
  [0.40841209 0.12490443 0.97794348]]

 [[0.16604975 0.70580662 0.86264544]
  [0.90620665 0.74972927 0.14203809]
  [0.30877171 0.08906972 0.99610805]]

 [[0.56822427 0.0854057  0.0963307 ]
  [0.6818448  0.38222701 0.60459068]
  [0.86791254 0.30740546 0.71871649]]]


1.3.4 Задание
Задача:
Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
import numpy as np

# Создаем матрицу размером 5x5
matrix = np.zeros((5, 5))

# Заполняем границы матрицы единицами
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


1.3.5 Задание
Задача:
Создайте массив и отсортируйте его по убыванию.

In [6]:
import numpy as np

array = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(-array) * -1)

[8 7 6 5 4 3 2 1]


1.3.6 Задание
Задача:
Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
import numpy as np

# Создаем матрицу размером 3x4
matrix = np.random.rand(3, 4)

print("Форма матрицы:", matrix.shape)
print("Размер матрицы:", matrix.size)
print("Размерность матрицы:", matrix.ndim)


Форма матрицы: (3, 4)
Размер матрицы: 12
Размерность матрицы: 2


2.2.1 Пример
Задача:
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [ ]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


2.2.2 Пример
Задача:
Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [ ]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5], ['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3 Пример
Задача:
Создайте новый фрейм данных.

In [ ]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38,25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

2.2.4 Пример
Задача:
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [34]:
import pandas as pd
url = 'https://hubofdata.ru/dataset/f426ad0e-8dc1-44e2-8b37-e361ccb7b564/resource/3d3c7a68-b047-48d2-94c0-54d01b1abb39/download/crime.csv'

dataframe = pd.read_csv(url, on_bad_lines='skip')
dataframe.head(5)

month  Total_crimes   Serious  Huge_damage  Ecological  Terrorism  \
0  01.01.2003      214587.0   88203.0      20162.0      1216.0      630.0   
1  01.02.2003      221928.0   88863.0      20889.0      1701.0      678.0   
2  01.03.2003      248452.0  101349.0      24053.0      1817.0      809.0   
3  01.04.2003      236299.0   91625.0      19754.0      2449.0      892.0   
4  01.05.2003      230931.0   89615.0      17519.0      3530.0      796.0   

   Extremism  Murder  Harm_to_health   Rape    Theft  Vehicle_theft  \
0       13.0  2749.0          5559.0  574.0  81014.0         3549.0   
1        5.0  2444.0          4732.0  515.0  95970.0         3697.0   
2       10.0  2864.0          4851.0  560.0  79420.0         4327.0   
3       10.0  2919.0          4722.0  668.0  95215.0         5345.0   
4       20.0  2713.0          4895.0  688.0  94505.0         6374.0   

   Fraud_scam  Hooligan    Drugs  Weapons  
0      7731.0   10560.0  16006.0   4661.0  
1      7607.0   10816.0  16839.0   5364.0  
2      9437.0   11813.0  20176.0   5938.0  
3      7824.0   12636.0  16614.0   5230.0  
4      7122.0   12234.0  14413.0   5112.0

2.2.5 Пример
Задача:
Пронализировать характеристики фрейма данных.

In [35]:
display(dataframe.head(2))
display(dataframe.tail(3))
display(dataframe.shape)
display(dataframe.describe())

month  Total_crimes  Serious  Huge_damage  Ecological  Terrorism  \
0  01.01.2003      214587.0  88203.0      20162.0      1216.0      630.0   
1  01.02.2003      221928.0  88863.0      20889.0      1701.0      678.0   

   Extremism  Murder  Harm_to_health   Rape    Theft  Vehicle_theft  \
0       13.0  2749.0          5559.0  574.0  81014.0         3549.0   
1        5.0  2444.0          4732.0  515.0  95970.0         3697.0   

   Fraud_scam  Hooligan    Drugs  Weapons  
0      7731.0   10560.0  16006.0   4661.0  
1      7607.0   10816.0  16839.0   5364.0

month  Total_crimes  Serious  Huge_damage  Ecological  Terrorism  \
202  01.11.2019      148104.0  31652.0      49623.0      1581.0      149.0   
203  01.12.2019      155512.0  38470.0      60742.0      1526.0      164.0   
204  01.01.2020      159172.0  44134.0      57020.0      1264.0      118.0   

     Extremism  Murder  Harm_to_health   Rape    Theft  Vehicle_theft  \
202       27.0   622.0          1467.0  246.0  57434.0         1344.0   
203       52.0   534.0          1644.0  134.0  63327.0         1374.0   
204       62.0   723.0          2075.0  296.0  53977.0         1092.0   

     Fraud_scam  Hooligan    Drugs  Weapons  
202     19794.0     132.0  11067.0   1742.0  
203     22588.0     155.0  13451.0   1754.0  
204     22189.0     153.0  15463.0   2104.0

(205, 16)

Total_crimes        Serious   Huge_damage   Ecological    Terrorism  \
count     205.000000     205.000000    205.000000   205.000000   205.000000   
mean   221279.019512   59068.487805  38402.039024  2592.463415   197.839024   
std     51720.759692   20501.515982  20755.286960  1028.101551   245.462645   
min    137657.000000   15755.000000   7424.000000  1216.000000    12.000000   
25%    180711.000000   42135.000000  21813.000000  1888.000000    57.000000   
50%    207550.000000   51426.000000  26357.000000  2322.000000   103.000000   
75%    254352.000000   78407.000000  59282.000000  3034.000000   184.000000   
max    359098.000000  108299.000000  87941.000000  6822.000000  1198.000000   

        Extremism       Murder  Harm_to_health         Rape          Theft  \
count  205.000000   205.000000      205.000000   205.000000     205.000000   
mean    59.473171  1451.400000     3276.024390   463.580488   92647.560976   
std     42.070500   687.713793     1013.861819   188.413369   25376.346430   
min      2.000000   534.000000     1467.000000   134.000000   50155.000000   
25%     26.000000   932.000000     2479.000000   322.000000   72533.000000   
50%     52.000000  1200.000000     3256.000000   419.000000   88095.000000   
75%     87.000000  1975.000000     4152.000000   574.000000  107555.000000   
max    174.000000  3099.000000     5578.000000  1027.000000  153394.000000   

       Vehicle_theft    Fraud_scam      Hooligan         Drugs      Weapons  
count     205.000000    205.000000    205.000000    205.000000   205.000000  
mean     4101.414634  15277.834146   1457.648780  17644.356098  2525.019512  
std      1565.682727   4114.474680   2560.889194   3068.123707   733.169890  
min      1092.000000   5687.000000    132.000000   7275.000000  1637.000000  
25%      2928.000000  12481.000000    261.000000  16006.000000  2029.000000  
50%      3923.000000  15303.000000    486.000000  17924.000000  2351.000000  
75%      5125.000000  18005.000000   1785.000000  19686.000000  2868.000000  
max      8251.000000  27980.000000  12636.000000  25187.000000  5938.000000

2.2.6 Пример
Задача:
Выберите индивидуальные данные или срезы фрейма данных.

In [12]:
dataframe.iloc[1:4]

month  Total_crimes   Serious  Huge_damage  Ecological  Terrorism  \
1  01.02.2003      221928.0   88863.0      20889.0      1701.0      678.0   
2  01.03.2003      248452.0  101349.0      24053.0      1817.0      809.0   
3  01.04.2003      236299.0   91625.0      19754.0      2449.0      892.0   

   Extremism  Murder  Harm_to_health   Rape    Theft  Vehicle_theft  \
1        5.0  2444.0          4732.0  515.0  95970.0         3697.0   
2       10.0  2864.0          4851.0  560.0  79420.0         4327.0   
3       10.0  2919.0          4722.0  668.0  95215.0         5345.0   

   Fraud_scam  Hooligan    Drugs  Weapons  
1      7607.0   10816.0  16839.0   5364.0  
2      9437.0   11813.0  20176.0   5938.0  
3      7824.0   12636.0  16614.0   5230.0

2.2.7 Пример
Задача:
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных на 01.02.2003.

In [ ]:
dataframe[dataframe['month'] == '01.02.2003'].head(2)

month  Total_crimes  Serious  Huge_damage  Ecological  Terrorism  \
1  01.02.2003      221928.0  88863.0      20889.0      1701.0      678.0   

   Extremism  Murder  Harm_to_health   Rape    Theft  Vehicle_theft  \
1        5.0  2444.0          4732.0  515.0  95970.0         3697.0   

   Fraud_scam  Hooligan    Drugs  Weapons  
1      7607.0   10816.0  16839.0   5364.0

2.3.1 Задание
Задача:
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [10]:
import pandas as pd
import numpy as np

a = pd.Series([3,4])
b = pd.Series([7,3])

# Расчет евклидова расстояния между Series a и b
euclidean_distance = np.sqrt(np.sum((a - b)**2))

# Вывод евклидова расстояния между Series a и b
print(euclidean_distance)


4.123105625617661


2.3.2 Задание
Задача:
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [36]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/credit_german.csv'

dataframe = pd.read_csv(url, on_bad_lines='skip')
dataframe.head(5)

checking_status  duration                    credit_history  \
0            '<0'         6  'critical/other existing credit'   
1      '0<=X<200'        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3            '<0'        42                   'existing paid'   
4            '<0'        24              'delayed previously'   

               purpose  credit_amount      savings_status employment  \
0             radio/tv           1169  'no known savings'      '>=7'   
1             radio/tv           5951              '<100'   '1<=X<4'   
2            education           2096              '<100'   '4<=X<7'   
3  furniture/equipment           7882              '<100'   '4<=X<7'   
4            'new car'           4870              '<100'   '1<=X<4'   

   installment_commitment       personal_status other_parties  ...  \
0                       4         'male single'          none  ...   
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   
4                       3         'male single'          none  ...   

    property_magnitude age  other_payment_plans     housing existing_credits  \
0        'real estate'  67                 none         own                2   
1        'real estate'  22                 none         own                1   
2        'real estate'  49                 none         own                1   
3     'life insurance'  45                 none  'for free'                1   
4  'no known property'  53                 none  'for free'                2   

                    job num_dependents  own_telephone foreign_worker class  
0               skilled              1            yes            yes  good  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  
4               skilled              2           none            yes   bad  

[5 rows x 21 columns]

2.3.3 Задание
Задача:
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [37]:
display(dataframe.head(2))
display(dataframe.tail(3))
display(dataframe.shape)
display(dataframe.describe())

checking_status  duration                    credit_history   purpose  \
0            '<0'         6  'critical/other existing credit'  radio/tv   
1      '0<=X<200'        48                   'existing paid'  radio/tv   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'      '>=7'                       4   
1           5951              '<100'   '1<=X<4'                       2   

        personal_status other_parties  ...  property_magnitude age  \
0         'male single'          none  ...       'real estate'  67   
1  'female div/dep/mar'          none  ...       'real estate'  22   

   other_payment_plans housing existing_credits      job num_dependents  \
0                 none     own                2  skilled              1   
1                 none     own                1  skilled              1   

   own_telephone foreign_worker class  
0            yes            yes  good  
1           none            yes   bad  

[2 rows x 21 columns]

checking_status  duration                    credit_history     purpose  \
997   'no checking'        12                   'existing paid'    radio/tv   
998            '<0'        45                   'existing paid'    radio/tv   
999      '0<=X<200'        45  'critical/other existing credit'  'used car'   

     credit_amount savings_status  employment  installment_commitment  \
997            804         '<100'       '>=7'                       4   
998           1845         '<100'    '1<=X<4'                       4   
999           4576   '100<=X<500'  unemployed                       3   

    personal_status other_parties  ...   property_magnitude age  \
997   'male single'          none  ...                  car  38   
998   'male single'          none  ...  'no known property'  23   
999   'male single'          none  ...                  car  27   

     other_payment_plans     housing existing_credits      job num_dependents  \
997                 none         own                1  skilled              1   
998                 none  'for free'                1  skilled              1   
999                 none         own                1  skilled              1   

     own_telephone foreign_worker class  
997           none            yes  good  
998            yes            yes   bad  
999           none            yes  good  

[3 rows x 21 columns]

(1000, 21)

duration  credit_amount  installment_commitment  residence_since  \
count  1000.000000    1000.000000             1000.000000      1000.000000   
mean     20.903000    3271.258000                2.973000         2.845000   
std      12.058814    2822.736876                1.118715         1.103718   
min       4.000000     250.000000                1.000000         1.000000   
25%      12.000000    1365.500000                2.000000         2.000000   
50%      18.000000    2319.500000                3.000000         3.000000   
75%      24.000000    3972.250000                4.000000         4.000000   
max      72.000000   18424.000000                4.000000         4.000000   

               age  existing_credits  num_dependents  
count  1000.000000       1000.000000     1000.000000  
mean     35.546000          1.407000        1.155000  
std      11.375469          0.577654        0.362086  
min      19.000000          1.000000        1.000000  
25%      27.000000          1.000000        1.000000  
50%      33.000000          1.000000        1.000000  
75%      42.000000          2.000000        1.000000  
max      75.000000          4.000000        2.000000

In [15]:
dataframe.iloc[1:4]

checking_status  duration                    credit_history  \
1      '0<=X<200'        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3            '<0'        42                   'existing paid'   

               purpose  credit_amount savings_status employment  \
1             radio/tv           5951         '<100'   '1<=X<4'   
2            education           2096         '<100'   '4<=X<7'   
3  furniture/equipment           7882         '<100'   '4<=X<7'   

   installment_commitment       personal_status other_parties  ...  \
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   

   property_magnitude age  other_payment_plans     housing existing_credits  \
1       'real estate'  22                 none         own                1   
2       'real estate'  49                 none         own                1   
3    'life insurance'  45                 none  'for free'                1   

                    job num_dependents  own_telephone foreign_worker class  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  

[3 rows x 21 columns]

In [31]:
dataframe[dataframe['duration'] == 6].head(3)

checking_status  duration                    credit_history  \
0             '<0'         6  'critical/other existing credit'   
21            '<0'         6                   'existing paid'   
25            '<0'         6                   'existing paid'   

                purpose  credit_amount      savings_status employment  \
0              radio/tv           1169  'no known savings'      '>=7'   
21             radio/tv           2647       '500<=X<1000'   '1<=X<4'   
25  furniture/equipment           1374              '<100'   '1<=X<4'   

    installment_commitment personal_status other_parties  ...  \
0                        4   'male single'          none  ...   
21                       2   'male single'          none  ...   
25                       1   'male single'          none  ...   

    property_magnitude age  other_payment_plans housing existing_credits  \
0        'real estate'  67                 none     own                2   
21       'real estate'  44                 none    rent                1   
25       'real estate'  36                 bank     own                1   

                     job num_dependents  own_telephone foreign_worker class  
0                skilled              1            yes            yes  good  
21               skilled              2           none            yes  good  
25  'unskilled resident'              1            yes            yes  good  

[3 rows x 21 columns]

3.2.1. Пример
Задача:
Прошкалируйте числовой признак в диапазон между двумя значениями.

In [ ]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,1))
scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2. Пример
Задача:
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [ ]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


3.2.3. Пример
Задача:
Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2 Задание
Задача:
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)

# Создание объектов для нормализации
min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

df['sepal_length_cm_normalized'] = min_max_scaler.fit_transform(df[['sepal_length_cm']])

df['sepal_width_cm_normalized'] = standard_scaler.fit_transform(df[['sepal_width_cm']])

print(df.head())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species  \
0              5.1             3.5              1.4             0.2  setosa   
1              4.9             3.0              1.4             0.2  setosa   
2              4.7             3.2              1.3             0.2  setosa   
3              4.6             3.1              1.5             0.2  setosa   
4              5.0             3.6              1.4             0.2  setosa   

   sepal_length_cm_normalized  sepal_width_cm_normalized  
0                    0.222222                   1.032057  
1                    0.166667                  -0.124958  
2                    0.111111                   0.337848  
3                    0.083333                   0.106445  
4                    0.194444                   1.263460  
